
name: my workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Package Registry
        run: echo "${{ secrets.CONTAINER_REGISTRY_PASSWORD }}" | docker login hub.docker.com -u "${{ secrets.CONTAINER_REGISTRY_USERNAME }}" --password-stdin